[package]
name = "ssm-to-ec2"
version = "0.1.0"
authors = ["Yuto Suzuki <yuutoo.advance@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_core = "0.45.0"
rusoto_ec2 = "0.45.0"
tokio = { version = "0.2", features = ["macros"] }
