name: note
on: push

jobs:
  note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install simple-git
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/script/prs.js`)
            console.log(script({github, context}))
